language: c

compiler:
  - clang
  - gcc

os: linux

env:
  - VARIANT=debug TRANSPORT=udp BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=debug TRANSPORT=tcp BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=debug TRANSPORT=dtls BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=debug TRANSPORT=pipe BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=release TRANSPORT=udp BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=release TRANSPORT=tcp BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=release TRANSPORT=dtls BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=release TRANSPORT=dtls BINDINGS=python ASAN=yes FSAN=yes
  - VARIANT=release TRANSPORT=pipe BINDINGS=python,go ASAN=yes FSAN=no
  - VARIANT=release TRANSPORT=fuzzer BINDINGS=python ASAN=yes FSAN=yes
jobs:
  exclude:
    - compiler: clang
    - compiler: gcc
      env: VARIANT=release TRANSPORT=dtls BINDINGS=python ASAN=yes FSAN=yes
    - compiler: gcc
      env: VARIANT=release TRANSPORT=fuzzer BINDINGS=python ASAN=yes FSAN=yes
  include:
    - compiler: clang
      env: VARIANT=release TRANSPORT=dtls BINDINGS=python ASAN=yes FSAN=yes
    - compiler: clang
      env: VARIANT=release TRANSPORT=fuzzer BINDINGS=python ASAN=yes FSAN=yes

dist: bionic
addons:
  apt:
    packages:
      - doxygen
      - nasm
      - scons
      - zlib1g-dev

before_install:
  - "[ $CC = gcc ] && export CC=gcc CXX=g++ || true"
  - "[ $CC = clang ] && export CC=clang CXX=clang++ || true"
  - . ./.travis/before_install-pyenv.sh
  - pyenv global 3.6

install:
  - ./.travis/install-swig.sh
  - pip install --user cryptography
  - pip install --user pexpect

script:
  - scons CC=$CC CXX=$CXX variant=$VARIANT transport=$TRANSPORT bindings=$BINDINGS asan=$ASAN ubsan=yes fsan=$FSAN;
  - ./test_scripts/run.py -d;
